<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Notification - Ed-Cademy</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f4f7fa; }
        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }
        .header { background: linear-gradient(135deg, #dc3545 0%, #6c757d 100%); padding: 40px 30px; text-align: center; }
        .header h1 { color: #ffffff; margin: 0; font-size: 24px; font-weight: 600; }
        .content { padding: 40px 30px; color: #333333; line-height: 1.6; }
        .alert-type { font-size: 16px; margin-bottom: 20px; font-weight: 600; }
        .notification-box {
            background-color: #f8f9fa;
            border-radius: 8px;
            padding: 25px;
            margin: 20px 0;
            border-left: 4px solid #dc3545;
        }
        .notification-box.urgent { border-left-color: #dc3545; background-color: #fff5f5; }
        .notification-box.info { border-left-color: #17a2b8; background-color: #f0f8ff; }
        .notification-box.success { border-left-color: #28a745; background-color: #f8fff8; }
        .notification-title { font-size: 18px; font-weight: 600; margin-bottom: 15px; color: #333; }
        .data-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 20px 0; }
        .data-item { background: #ffffff; padding: 15px; border-radius: 6px; border: 1px solid #e9ecef; }
        .data-label { font-weight: 600; color: #666; font-size: 12px; text-transform: uppercase; margin-bottom: 5px; }
        .data-value { color: #333; font-size: 14px; }
        .action-required { background-color: #fff3cd; border: 1px solid #ffeaa7; border-radius: 8px; padding: 20px; margin: 20px 0; }
        .action-title { font-weight: 600; color: #856404; margin-bottom: 10px; }
        .cta-button { display: inline-block; background: linear-gradient(135deg, #dc3545 0%, #6c757d 100%); color: #ffffff; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: 600; margin: 20px 0; }
        .footer { background-color: #f8f9fa; padding: 30px; text-align: center; color: #666666; font-size: 14px; }
        .footer a { color: #dc3545; text-decoration: none; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔔 Admin Notification</h1>
        </div>

        <div class="content">
            <div class="alert-type">
                {{ ucfirst($type) }} Alert
            </div>

            <div class="notification-box {{ $type == 'urgent' ? 'urgent' : ($type == 'success' ? 'success' : 'info') }}">
                <div class="notification-title">{{ $message }}</div>

                @if($data)
                    <div class="data-grid">
                        @foreach($data as $key => $value)
                            <div class="data-item">
                                <div class="data-label">{{ ucwords(str_replace('_', ' ', $key)) }}</div>
                                <div class="data-value">{{ $value }}</div>
                            </div>
                        @endforeach
                    </div>
                @endif
            </div>

            @if($type == 'urgent' || $type == 'warning')
            <div class="action-required">
                <div class="action-title">⚠️ Action Required:</div>
                <p>Please review this notification and take appropriate action in the admin dashboard.</p>
            </div>
            @endif

            <div style="text-align: center;">
                <a href="{{ $adminUrl }}" class="cta-button">View Admin Dashboard</a>
            </div>

            <p><strong>Notification Details:</strong></p>
            <ul>
                <li><strong>Type:</strong> {{ ucfirst($type) }}</li>
                <li><strong>Time:</strong> {{ now()->format('M j, Y \a\t g:i A') }}</li>
                <li><strong>Priority:</strong> {{ $type == 'urgent' ? 'High' : ($type == 'warning' ? 'Medium' : 'Normal') }}</li>
            </ul>

            <p>This notification was automatically generated by the Ed-Cademy system. Please check the admin dashboard for more details and to take any necessary actions.</p>

            <p><strong>Ed-Cademy Admin System</strong></p>
        </div>

        <div class="footer">
            <p>
                This is an automated notification from the Ed-Cademy admin system.
            </p>
            <p>
                <a href="{{ route('web.privacy.policy') }}">Privacy Policy</a> |
                <a href="{{ route('web.terms.and.conditions') }}">Terms of Service</a>
            </p>
        </div>
    </div>
</body>
</html>