<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class BlogController extends Controller
{
    public function index(Request $request)
    {
        $query = Blog::query();

        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        if ($request->filled('q')) {
            $search = trim((string) $request->q);
            $query->where(function ($q) use ($search) {
                $q->where('title', 'like', '%' . $search . '%')
                    ->orWhere('author', 'like', '%' . $search . '%')
                    ->orWhere('tags', 'like', '%' . $search . '%');
            });
        }

        $blogs = $query->latest()->paginate(15)->appends($request->query());

        return view('admin.blogs.index', compact('blogs'));
    }

    public function create()
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();
        $defaultAuthor = $user->full_name ?: $user->email;

        return view('admin.blogs.create', compact('defaultAuthor'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'author' => ['nullable', 'string', 'max:255'],
            'status' => ['required', 'in:draft,published'],
            'tags' => ['nullable', 'string', 'max:255'],
            'content' => ['required', 'string'],
            'image' => ['nullable', 'image', 'max:2048'],
        ]);

        /** @var \App\Models\User $user */
        $user = Auth::user();

        $blog = new Blog();
        $blog->title = $validated['title'];
        $blog->author = $validated['author'] ?: ($user->full_name ?: $user->email);
        $blog->status = $validated['status'];
        $blog->tags = $validated['tags'] ?? null;
        $blog->content = $validated['content'];

        if ($request->hasFile('image')) {
            $blog->image = $this->storeImage($request->file('image'));
        }

        $blog->save();

        return redirect()->route('admin.blogs.index')->with('success', 'Blog created.');
    }

    public function edit(Blog $blog)
    {
        return view('admin.blogs.edit', compact('blog'));
    }

    public function update(Request $request, Blog $blog)
    {
        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'author' => ['nullable', 'string', 'max:255'],
            'status' => ['required', 'in:draft,published'],
            'tags' => ['nullable', 'string', 'max:255'],
            'content' => ['required', 'string'],
            'image' => ['nullable', 'image', 'max:2048'],
            'remove_image' => ['nullable', 'in:1'],
        ]);

        $blog->title = $validated['title'];
        $blog->author = $validated['author'] ?: $blog->author;
        $blog->status = $validated['status'];
        $blog->tags = $validated['tags'] ?? null;
        $blog->content = $validated['content'];

        if (($validated['remove_image'] ?? null) === '1') {
            $blog->image = null;
        }

        if ($request->hasFile('image')) {
            $blog->image = $this->storeImage($request->file('image'));
        }

        // If slug empty (older records), it will be generated by model hook.
        $blog->save();

        return redirect()->route('admin.blogs.index')->with('success', 'Blog updated.');
    }

    public function destroy(Blog $blog)
    {
        $blog->delete();

        return back()->with('success', 'Blog deleted.');
    }

    private function storeImage($file): string
    {
        $dir = public_path('uploads/blogs');
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $name = 'blog_' . time() . '_' . Str::random(6) . '.' . $file->getClientOriginalExtension();
        $file->move($dir, $name);

        return 'uploads/blogs/' . $name;
    }
}

